Repository mdn/mdn-minimalist, pull requests merged in 2020-12, with the labels that each got.

#311 fix: good and bad code examples
  sass/atoms/_code.scss
  sass/vars/_color-palette.scss
Labels: design-system

#312 chore: release 0.4.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#314 fix: improved link color
  sass/atoms/_links.scss
  sass/atoms/_tables.scss
  sass/vars/_color-palette.scss
Labels: design-system

#315 chore: release 0.4.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#318 Update yarn copy to make public directory if it does not exist
  package.json
Labels: community

#327 fix: release please
  .github/workflows/release-please.yml
Labels: devops

#329 fix: no heading no icon - notecards
  sass/atoms/_notecards.scss
Labels: design-system

#330 fix: highlighted link state
  sass/mixins/_links.scss
  test/sass/_test-mixins-links.scss
Labels: design-system

#331 fix: button interaction states
  sass/atoms/_buttons.scss
  sass/mdn-minimalist.scss
  sass/mixins/_buttons.scss
  sass/vars/_shadows.scss
  test/sass/_test-mixins-buttons.scss
Labels: design-system

#328 chore: release 0.4.7
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#333 feat: slow pulse animation
  sass/mixins/_animation.scss
Labels: design-system

#334 chore: release 0.5.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#336 fix: add metadata grid section
  sass/grid/_document.scss
  sass/mdn-minimalist.scss
Labels: design-system

#337 chore: release 0.5.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#340 fix: switch to small type scale - mobile
  sass/vars/_typography.scss
Labels: design-system

#341 chore: release 0.5.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#343 fix: prism theme update
  sass/atoms/_primsjs.scss
Labels: bug

#344 chore: release 0.5.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#359 fix: margins
  sass/atoms/_code.scss
  sass/atoms/_kbd.scss
  sass/atoms/_pre.scss
  sass/mdn-minimalist.scss
Labels: design-system

#360 chore: release 0.5.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#361 fix: remove missed top margins
  sass/atoms/_examples.scss
  sass/atoms/_notecards.scss
Labels: design-system

#362 chore: release 0.5.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#368 fix: update to properties table color
  sass/atoms/_tables.scss
  sass/vars/_borders.scss
Labels: design-system

#370 fix: update pre element border color
  sass/vars/_borders.scss
Labels: design-system

#371 fix: inline notecards with missing icons
  sass/atoms/_notecards.scss
Labels: design-system

#372 fix: blockquote style
  sass/atoms/_blockquote.scss
  sass/mdn-minimalist.scss
  sass/mixins/_typography.scss
  sass/vars/_color-palette.scss
Labels: design-system, enhancement

#369 chore: release 0.5.6
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#376 fix: readable line length
  sass/mixins/_typography.scss
  sass/mixins/_utils.scss
  test/sass/_test-mixins-utils.scss
Labels: design-system, enhancement

#377 chore: release 0.5.7
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#387 chore: Allow Dependabot bumps for GitHub Actions
  .github/dependabot.yml
Labels: devops
