Repository mdn/mdn-minimalist, pull requests merged in 2021-01, with the labels that each got.

#400 Add `white-space: nowrap` to kbd element
  sass/atoms/_kbd.scss
Labels: bug

#416 fix: callout style update
  sass/atoms/_callout.scss
Labels: bug

#402 chore: release 0.6.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#414 Attempt to fix table overflow-x
  sass/atoms/_tables.scss
Labels: community

#423 fix: update same-code-frame style
  sass/atoms/_examples.scss
Labels: bug

#424 chore: release 0.6.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#428 fix: page overlay stacking order
  sass/atoms/_overlays.scss
Labels: bug

#429 chore: release 0.6.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#439 chore: release 0.7.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#454 fix: add support for additional heading levels
  sass/atoms/_notecards.scss
Labels: a11y, enhancement

#455 chore: release 0.7.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending
